### ISSUE TITLE
Web interface for Meta data of uploaded files such as title, description, keywords, category, etc. (6 pts)

### ISSUE THREAD

**Issue by rhay-repo** [rhay-repo/MeTube-U8#18]
Constraint: A user must be signed into the system to be able to upload multimedia files.

- [x] private/public permissions
- [x] view title
- [x] view description
- [x] view keywords
- [x] view category
- [x] view owner
- [ ] view media
- [x] buttons for channel
- [x] buttons for friend
- [x] buttons for download
- [x] buttons for subscribe
- [ ] buttons working
- [ ] dynamic media content
- [x] favorite button
